"""Generate a CMake package config into an installed cvcpkg prefix.

`cvcpkg install` calls :func:`write_cmake_config` after populating a prefix
so that downstream projects can do::

    find_package(cvcpkg CONFIG REQUIRED)   # or find_package(libcvc-deps ...)

without any manual ``-DCMAKE_PREFIX_PATH=...``.  The generated config
prepends the prefix to ``CMAKE_PREFIX_PATH`` (and ``PKG_CONFIG_PATH``) so
subsequent ``find_package(Boost|Qt6|VTK|...)`` calls resolve in the prefix.

We emit the files directly (rather than via CMake's
``configure_package_config_file``) because ``cvcpkg install`` does not run
CMake — the emitted text is the fully-expanded equivalent.
"""

from __future__ import annotations

from pathlib import Path

# The standard preamble that CMake's ``@PACKAGE_INIT@`` expands to, minus the
# parts we don't need.  ``PACKAGE_PREFIX_DIR`` resolves to the prefix root:
# the config lives at ``<prefix>/lib/cmake/<name>/`` — three levels down.
_PACKAGE_INIT = """\
get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

macro(set_and_check _var _file)
  set(${_var} "${_file}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "${_var} references a missing path: ${_file}")
  endif()
endmacro()

macro(check_required_components _NAME)
  foreach(comp ${${_NAME}_FIND_COMPONENTS})
    if(NOT ${_NAME}_${comp}_FOUND)
      if(${_NAME}_FIND_REQUIRED_${comp})
        set(${_NAME}_FOUND FALSE)
      endif()
    endif()
  endforeach()
endmacro()
"""


def _cvcpkg_config(version: str) -> str:
    return (
        "# cvcpkgConfig.cmake — generated by `cvcpkg install`.  Do not edit.\n"
        "#\n"
        "# find_package(cvcpkg CONFIG REQUIRED) prepends this prefix to\n"
        "# CMAKE_PREFIX_PATH so later find_package() calls resolve here.\n\n"
        + _PACKAGE_INIT
        + f'\nset(CVCPKG_VERSION   "{version}")\n'
        + 'set(CVCPKG_ROOT_DIR  "${PACKAGE_PREFIX_DIR}")\n\n'
        + 'if(NOT "${CVCPKG_ROOT_DIR}" IN_LIST CMAKE_PREFIX_PATH)\n'
        + '  list(PREPEND CMAKE_PREFIX_PATH "${CVCPKG_ROOT_DIR}")\n'
        + "endif()\n\n"
        + 'if(IS_DIRECTORY "${CVCPKG_ROOT_DIR}/lib/pkgconfig")\n'
        + "  if(DEFINED ENV{PKG_CONFIG_PATH})\n"
        + '    set(ENV{PKG_CONFIG_PATH} "${CVCPKG_ROOT_DIR}/lib/pkgconfig:$ENV{PKG_CONFIG_PATH}")\n'
        + "  else()\n"
        + '    set(ENV{PKG_CONFIG_PATH} "${CVCPKG_ROOT_DIR}/lib/pkgconfig")\n'
        + "  endif()\n"
        + "endif()\n\n"
        + "set(cvcpkg_FOUND TRUE)\n\n"
        + "# Backward-compat aliases for the old libcvc-deps name.\n"
        + 'set(LIBCVC_DEPS_VERSION   "${CVCPKG_VERSION}")\n'
        + 'set(LIBCVC_DEPS_ROOT_DIR  "${CVCPKG_ROOT_DIR}")\n'
        + "set(libcvc-deps_FOUND     TRUE)\n\n"
        + "check_required_components(cvcpkg)\n"
    )


def _version_file(version: str) -> str:
    # AnyNewerVersion compatibility (any installed version >= requested).
    return (
        f'set(PACKAGE_VERSION "{version}")\n\n'
        "if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)\n"
        "  set(PACKAGE_VERSION_COMPATIBLE FALSE)\n"
        "else()\n"
        "  set(PACKAGE_VERSION_COMPATIBLE TRUE)\n"
        "  if(PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION)\n"
        "    set(PACKAGE_VERSION_EXACT TRUE)\n"
        "  endif()\n"
        "endif()\n"
    )


def _libcvc_deps_config(version: str) -> str:
    return (
        "# libcvc-depsConfig.cmake — backward-compat wrapper generated by cvcpkg.\n"
        "# Lets find_package(libcvc-deps CONFIG REQUIRED) keep working after the\n"
        "# rename to cvcpkg.\n\n"
        'get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)\n\n'  # noqa: E501
        "find_package(cvcpkg CONFIG QUIET\n"
        '  PATHS "${PACKAGE_PREFIX_DIR}"\n'
        "  NO_DEFAULT_PATH)\n\n"
        "if(cvcpkg_FOUND)\n"
        '  set(LIBCVC_DEPS_VERSION   "${CVCPKG_VERSION}")\n'
        '  set(LIBCVC_DEPS_ROOT_DIR  "${CVCPKG_ROOT_DIR}")\n'
        "  set(libcvc-deps_FOUND     TRUE)\n"
        "else()\n"
        f'  set(LIBCVC_DEPS_VERSION   "{version}")\n'
        '  set(LIBCVC_DEPS_ROOT_DIR  "${PACKAGE_PREFIX_DIR}")\n'
        '  if(NOT "${LIBCVC_DEPS_ROOT_DIR}" IN_LIST CMAKE_PREFIX_PATH)\n'
        '    list(PREPEND CMAKE_PREFIX_PATH "${LIBCVC_DEPS_ROOT_DIR}")\n'
        "  endif()\n"
        "  set(libcvc-deps_FOUND TRUE)\n"
        "endif()\n"
    )


def write_cmake_config(prefix: Path, version: str) -> list[Path]:
    """Write cvcpkg's CMake package config into *prefix*.

    Creates, under ``<prefix>/lib/cmake``:

    - ``cvcpkg/cvcpkgConfig.cmake`` + ``cvcpkg/cvcpkgConfigVersion.cmake``
    - ``libcvc-deps/libcvc-depsConfig.cmake`` (backward-compat wrapper)

    Returns the list of files written.
    """
    prefix = Path(prefix)
    written: list[Path] = []

    cvc_dir = prefix / "lib" / "cmake" / "cvcpkg"
    cvc_dir.mkdir(parents=True, exist_ok=True)
    for name, content in (
        ("cvcpkgConfig.cmake", _cvcpkg_config(version)),
        ("cvcpkgConfigVersion.cmake", _version_file(version)),
    ):
        path = cvc_dir / name
        path.write_text(content)
        written.append(path)

    compat_dir = prefix / "lib" / "cmake" / "libcvc-deps"
    compat_dir.mkdir(parents=True, exist_ok=True)
    for name, content in (
        ("libcvc-depsConfig.cmake", _libcvc_deps_config(version)),
        ("libcvc-depsConfigVersion.cmake", _version_file(version)),
    ):
        path = compat_dir / name
        path.write_text(content)
        written.append(path)

    return written
