#!/usr/bin/env bash
# recipes/vcglib/build.sh — stage header-only vcglib into the prefix.
#
# vcglib has no compiled libraries.  This script installs:
#   <prefix>/include/vcg/       — vcg headers
#   <prefix>/include/wrap/      — wrap headers
#   <prefix>/share/vcglib/      — full source tree (for add_subdirectory)
#   <prefix>/share/cmake/vcglib — CMake package config
set -euo pipefail

SRC="${CVC_SOURCE_DIR:?}"
DST="${CVC_INSTALL_DIR:?}"

mkdir -p "$DST/include" \
         "$DST/share/vcglib" \
         "$DST/share/cmake/vcglib"

# Header roots for plain #include <vcg/...> / #include <wrap/...>
cp -R "$SRC/vcg"  "$DST/include/vcg"
cp -R "$SRC/wrap" "$DST/include/wrap"

# Full source tree for add_subdirectory() consumers
cp -R "$SRC/." "$DST/share/vcglib/"

# ── CMake package config ──
cat > "$DST/share/cmake/vcglib/vcglib-config.cmake" << 'CMAKE'
# vcglib-config.cmake — generated by cvcpkg (libcvc-deps)
include(CMakeFindDependencyMacro)
find_dependency(Eigen3 QUIET)

if(NOT TARGET vcglib::vcglib)
  add_library(vcglib::vcglib INTERFACE IMPORTED)
  get_filename_component(_vcglib_root
    "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
  set_target_properties(vcglib::vcglib PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${_vcglib_root}/include"
    INTERFACE_COMPILE_FEATURES    "cxx_std_11")
  if(MSVC)
    set_property(TARGET vcglib::vcglib APPEND PROPERTY
      INTERFACE_COMPILE_OPTIONS "/bigobj")
  endif()
  if(TARGET Eigen3::Eigen)
    set_property(TARGET vcglib::vcglib APPEND PROPERTY
      INTERFACE_LINK_LIBRARIES Eigen3::Eigen)
  endif()
endif()
CMAKE

# ── CMake version file ──
VCGLIB_VERSION="${CVC_VERSION:-2025.07}"
cat > "$DST/share/cmake/vcglib/vcglib-config-version.cmake" << CMAKE
set(PACKAGE_VERSION "${VCGLIB_VERSION}")
if("\${PACKAGE_FIND_VERSION}" STREQUAL "")
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
elseif("\${PACKAGE_FIND_VERSION}" VERSION_EQUAL "\${PACKAGE_VERSION}")
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
  set(PACKAGE_VERSION_EXACT TRUE)
elseif("\${PACKAGE_FIND_VERSION}" VERSION_LESS "\${PACKAGE_VERSION}")
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
else()
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
endif()
CMAKE

echo "vcglib ${VCGLIB_VERSION} staged into ${DST}"
