#!/usr/bin/env bash
# recipes/swig/build.sh — build SWIG from source on Linux and macOS.
#
# SWIG 4.4.1 supports JavaScript/Emscripten target for WASM output.
# Uses PCRE2 from the cvcpkg prefix (built as a separate recipe).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "${SCRIPT_DIR}/../_common/env-${CVC_PLATFORM}.sh"

# Put the cvcpkg prefix bin on PATH so bison from our recipe is found.
export PATH="${CVC_DEPS_PREFIX}/bin:${PATH}"

# Bison's compiled-in PKGDATADIR points to the original build host.
# Override it so bison finds its m4sugar data in the deps prefix.
export BISON_PKGDATADIR="${CVC_DEPS_PREFIX}/share/bison"

# Fix Perl module paths for cvcpkg-built automake on BSDs.
# The aclocal script has hardcoded Perl paths from the build host; PERL5LIB
# lets Perl find the Automake modules at their actual installed location.
_am_share=$(find "${CVC_DEPS_PREFIX}/share" -maxdepth 1 -name 'automake-*' -type d 2>/dev/null | head -1)
if [[ -n "${_am_share}" ]]; then
    export PERL5LIB="${_am_share}${PERL5LIB:+:$PERL5LIB}"
fi

cd "${CVC_SOURCE_DIR}"

# SWIG uses autotools; run autogen if configure doesn't exist.
if [[ ! -f configure ]]; then
    ./autogen.sh
fi

# Use PCRE2 from the cvcpkg deps prefix.
PCRE2_CONFIG="${CVC_DEPS_PREFIX}/bin/pcre2-config"
if [[ ! -x "${PCRE2_CONFIG}" ]]; then
    echo "ERROR: pcre2-config not found at ${PCRE2_CONFIG}" >&2
    echo "       Build the pcre2 recipe first: cvcpkg build pcre2" >&2
    exit 1
fi

./configure \
    --prefix="${CVC_INSTALL_DIR}" \
    --with-pcre2-prefix="${CVC_DEPS_PREFIX}"

make -j "${CVC_JOBS}"
make install

# Generate a CMake config file so find_package(SWIG) works inside bundles.
SWIG_VER=$("${CVC_INSTALL_DIR}/bin/swig" -version | sed -n 's/.*SWIG Version \([0-9.]*\).*/\1/p')
mkdir -p "${CVC_INSTALL_DIR}/lib/cmake/SWIG"
cat > "${CVC_INSTALL_DIR}/lib/cmake/SWIG/SWIGConfig.cmake" <<EOF
# Generated by cvcpkg swig recipe.
set(SWIG_EXECUTABLE "\${CMAKE_CURRENT_LIST_DIR}/../../../bin/swig")
set(SWIG_DIR "\${CMAKE_CURRENT_LIST_DIR}/../../../share/swig/${SWIG_VER}")
set(SWIG_VERSION "${SWIG_VER}")
set(SWIG_FOUND TRUE)
EOF
cat > "${CVC_INSTALL_DIR}/lib/cmake/SWIG/SWIGConfigVersion.cmake" <<EOF
set(PACKAGE_VERSION "${SWIG_VER}")
if("\${PACKAGE_FIND_VERSION}" VERSION_LESS_EQUAL PACKAGE_VERSION)
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    if("\${PACKAGE_FIND_VERSION}" VERSION_EQUAL PACKAGE_VERSION)
        set(PACKAGE_VERSION_EXACT TRUE)
    endif()
endif()
EOF
