#!/usr/bin/env bash
# recipes/skia/build.sh — clone + GN build Skia on Linux/macOS.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "${SCRIPT_DIR}/../_common/env-${CVC_PLATFORM}.sh"

SKIA_TAG="chrome/m137"

# --- 1. Clone (or update) skia. ---
SRC="${CVC_SOURCE_DIR}/skia"
if [[ ! -d "${SRC}/.git" ]]; then
    git clone --depth=1 --branch "${SKIA_TAG}" https://skia.googlesource.com/skia.git "${SRC}"
fi
cd "${SRC}"

# --- 2. Sync DEPS. ---
python3 tools/git-sync-deps

# --- 3. GN args. ---
if [[ "${CVC_LINK:-shared}" == "static" ]]; then
    IS_COMPONENT="false"
else
    IS_COMPONENT="true"
fi

case "${CVC_PLATFORM}" in
    linux)
        GN_TARGET_OS='"linux"'
        ;;
    macos)
        GN_TARGET_OS='"mac"'
        ;;
esac

GN_ARGS="is_official_build=true is_component_build=${IS_COMPONENT} \
skia_use_system_expat=false skia_use_system_freetype2=false \
skia_use_system_harfbuzz=false skia_use_system_icu=false \
skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false \
skia_use_system_libwebp=false skia_use_system_zlib=false \
skia_enable_tools=false skia_enable_gpu=true \
target_os=${GN_TARGET_OS} extra_cflags=[\"-fPIC\"]"

OUT="${CVC_BUILD_DIR}/out"
bin/gn gen "${OUT}" --args="${GN_ARGS}"
ninja -C "${OUT}" -j "${CVC_JOBS}" skia skshaper skparagraph skunicode

# --- 4. Stage headers + libs. ---
mkdir -p "${CVC_INSTALL_DIR}/include/skia" \
         "${CVC_INSTALL_DIR}/lib" \
         "${CVC_INSTALL_DIR}/share/skia"

for pat in libskia.* libskshaper.* libskparagraph.* libskunicode.*; do
    cp "${OUT}"/${pat} "${CVC_INSTALL_DIR}/lib/" 2>/dev/null || true
done

# Copy public headers (include/), modules headers, and gn/ tool metadata.
cp -R include/* "${CVC_INSTALL_DIR}/include/skia/"
for m in modules/skshaper/include modules/skparagraph/include modules/skunicode/include; do
    if [[ -d "$m" ]]; then
        cp -R "$m"/* "${CVC_INSTALL_DIR}/include/skia/"
    fi
done

# --- 5. Minimal CMake package config. ---
mkdir -p "${CVC_INSTALL_DIR}/lib/cmake/Skia"
cat > "${CVC_INSTALL_DIR}/lib/cmake/Skia/SkiaConfig.cmake" << 'CMAKE'
# SkiaConfig.cmake — generated by cvcpkg (libcvc-deps)
get_filename_component(_skia_root "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)

foreach(_lib skia skshaper skparagraph skunicode)
    if(NOT TARGET Skia::${_lib})
        add_library(Skia::${_lib} UNKNOWN IMPORTED)
        find_library(_skia_${_lib}_path NAMES ${_lib} HINTS "${_skia_root}/lib" NO_DEFAULT_PATH)
        set_target_properties(Skia::${_lib} PROPERTIES
            IMPORTED_LOCATION             "${_skia_${_lib}_path}"
            INTERFACE_INCLUDE_DIRECTORIES "${_skia_root}/include/skia"
            INTERFACE_COMPILE_FEATURES    "cxx_std_17")
    endif()
endforeach()
CMAKE

echo "skia (chrome/m137) installed to ${CVC_INSTALL_DIR}"
