#!/usr/bin/env bash
# recipes/wasmtime/build.sh — stage pre-built Wasmtime C API on Linux/macOS.
set -euo pipefail

WASMTIME_VER="45.0.0"

: "${CVC_INSTALL_DIR:?CVC_INSTALL_DIR must be set}"

# Determine the correct artifact name.
ARCH="$(uname -m)"
case "${CVC_PLATFORM}" in
    linux)
        [[ "${ARCH}" == "aarch64" ]] && ARCH="aarch64" || ARCH="x86_64"
        ARTIFACT="wasmtime-v${WASMTIME_VER}-${ARCH}-linux-c-api.tar.xz"
        ;;
    macos)
        [[ "${ARCH}" == "arm64" ]] && ARCH="aarch64" || ARCH="x86_64"
        ARTIFACT="wasmtime-v${WASMTIME_VER}-${ARCH}-macos-c-api.tar.xz"
        ;;
    *)
        echo "Unsupported platform: ${CVC_PLATFORM}" >&2
        exit 1
        ;;
esac

URL="https://github.com/bytecodealliance/wasmtime/releases/download/v${WASMTIME_VER}/${ARTIFACT}"
DOWNLOAD_DIR="${CVC_BUILD_DIR:-/tmp}"

echo "Downloading ${ARTIFACT}..."
curl -fSL -o "${DOWNLOAD_DIR}/${ARTIFACT}" "${URL}"

# Extract — the tarball contains a top-level directory.
mkdir -p "${DOWNLOAD_DIR}/wasmtime-extracted"
tar xf "${DOWNLOAD_DIR}/${ARTIFACT}" -C "${DOWNLOAD_DIR}/wasmtime-extracted" --strip-components=1

SRC="${DOWNLOAD_DIR}/wasmtime-extracted"

# Stage headers.
mkdir -p "${CVC_INSTALL_DIR}/include/wasmtime"
cp "${SRC}"/include/wasmtime.h "${CVC_INSTALL_DIR}/include/"
cp "${SRC}"/include/wasm.h    "${CVC_INSTALL_DIR}/include/"
cp "${SRC}"/include/wasi.h    "${CVC_INSTALL_DIR}/include/"
if [[ -d "${SRC}/include/wasmtime" ]]; then
    cp -r "${SRC}"/include/wasmtime/* "${CVC_INSTALL_DIR}/include/wasmtime/"
fi

# Stage libraries.
mkdir -p "${CVC_INSTALL_DIR}/lib"
cp "${SRC}"/lib/libwasmtime* "${CVC_INSTALL_DIR}/lib/" 2>/dev/null || true

# Generate CMake config.
mkdir -p "${CVC_INSTALL_DIR}/lib/cmake/wasmtime"
cat > "${CVC_INSTALL_DIR}/lib/cmake/wasmtime/wasmtimeConfig.cmake" <<'EOF'
# Generated by cvcpkg wasmtime recipe.
get_filename_component(_WASMTIME_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)

add_library(wasmtime::wasmtime UNKNOWN IMPORTED)
find_library(_WASMTIME_LIB NAMES wasmtime PATHS "${_WASMTIME_PREFIX}/lib" NO_DEFAULT_PATH)
set_target_properties(wasmtime::wasmtime PROPERTIES
    IMPORTED_LOCATION "${_WASMTIME_LIB}"
    INTERFACE_INCLUDE_DIRECTORIES "${_WASMTIME_PREFIX}/include"
)
# Wasmtime's C API requires pthreads and dl on UNIX.
if(UNIX)
    set_property(TARGET wasmtime::wasmtime APPEND PROPERTY
        INTERFACE_LINK_LIBRARIES pthread dl m)
endif()

set(wasmtime_FOUND TRUE)
unset(_WASMTIME_PREFIX)
unset(_WASMTIME_LIB)
EOF

cat > "${CVC_INSTALL_DIR}/lib/cmake/wasmtime/wasmtimeConfigVersion.cmake" <<EOF
set(PACKAGE_VERSION "${WASMTIME_VER}")
if("\${PACKAGE_FIND_VERSION}" VERSION_LESS_EQUAL PACKAGE_VERSION)
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    if("\${PACKAGE_FIND_VERSION}" VERSION_EQUAL PACKAGE_VERSION)
        set(PACKAGE_VERSION_EXACT TRUE)
    endif()
endif()
EOF

echo "Wasmtime ${WASMTIME_VER} C API staged to ${CVC_INSTALL_DIR}"
