#!/usr/bin/env bash
# recipes/imgui/build.sh — compile the Dear ImGui core into libimgui and
# install headers + backend sources.
#
# ImGui ships no CMake install, so we compile the core translation units by
# hand.  CVC_LINK=static  → a static archive (libimgui.a);
# CVC_LINK=shared → a shared library (libimgui.so / libimgui.dylib).
# The backends/ directory is shipped as SOURCE (headers + .cpp/.mm) so the
# consumer compiles the platform/renderer glue it actually needs.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1090
source "${SCRIPT_DIR}/../_common/env-${CVC_PLATFORM}.sh"

cd "${CVC_SOURCE_DIR}"

mkdir -p "${CVC_INSTALL_DIR}/lib" \
         "${CVC_INSTALL_DIR}/include/imgui" \
         "${CVC_INSTALL_DIR}/include/imgui/backends"

# Compile the platform-agnostic core translation units.
_srcs=( imgui.cpp imgui_draw.cpp imgui_tables.cpp imgui_widgets.cpp imgui_demo.cpp )
for _s in "${_srcs[@]}"; do
    "${CXX}" -std=c++17 -fPIC -O2 -I. -c "${_s}" -o "${_s%.cpp}.o"
done

if [[ "${CVC_LINK:-shared}" == "static" ]]; then
    ar rcs "${CVC_INSTALL_DIR}/lib/libimgui.a" ./*.o
    _imgui_lib=libimgui.a
elif [[ "${CVC_PLATFORM}" == "macos" ]]; then
    "${CXX}" -dynamiclib -install_name "@rpath/libimgui.dylib" \
        -o "${CVC_INSTALL_DIR}/lib/libimgui.dylib" ./*.o
    _imgui_lib=libimgui.dylib
else
    "${CXX}" -shared -Wl,-soname,libimgui.so \
        -o "${CVC_INSTALL_DIR}/lib/libimgui.so" ./*.o
    _imgui_lib=libimgui.so
fi

# Install public headers.
cp imgui.h imconfig.h imgui_internal.h \
   imstb_rectpack.h imstb_textedit.h imstb_truetype.h \
   "${CVC_INSTALL_DIR}/include/imgui/"

# Ship the whole backends/ tree (headers, .cpp, .mm, sub-dirs) as source.
cp -R backends/. "${CVC_INSTALL_DIR}/include/imgui/backends/"

# Emit a relocatable cmake package config so consumers can find_package(imgui)
# and link the imgui::imgui imported target — no bare -limgui, no per-consumer
# -L path. ImGui ships no cmake install, so we generate it here. The prefix is
# derived from this file's own location at configure time, so it survives
# cvcpkg's path relocation with nothing to rewrite.
mkdir -p "${CVC_INSTALL_DIR}/lib/cmake/imgui"
cat > "${CVC_INSTALL_DIR}/lib/cmake/imgui/imguiConfig.cmake" <<CFG
# Dear ImGui — cmake package config generated by the cvcpkg imgui recipe.
get_filename_component(_imgui_prefix "\${CMAKE_CURRENT_LIST_DIR}/../../.." REALPATH)
if(NOT TARGET imgui::imgui)
  add_library(imgui::imgui UNKNOWN IMPORTED)
  set_target_properties(imgui::imgui PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "\${_imgui_prefix}/include/imgui"
    IMPORTED_LOCATION "\${_imgui_prefix}/lib/${_imgui_lib}")
endif()
unset(_imgui_prefix)
CFG
cat > "${CVC_INSTALL_DIR}/lib/cmake/imgui/imguiConfigVersion.cmake" <<'VER'
# Keep PACKAGE_VERSION in sync with the recipe's upstream_version.
set(PACKAGE_VERSION "1.92.9")
if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
  if(PACKAGE_VERSION VERSION_EQUAL PACKAGE_FIND_VERSION)
    set(PACKAGE_VERSION_EXACT TRUE)
  endif()
endif()
VER

cvc_rewrite_install_paths
