schema_version: 1
recipe:
  name: xcb-util-keysyms
  upstream_version: "0.4.1"
  cvc_revision: 2
  maintainer: "cvcpkg group"
  maintainer_email: "info@cvcpkg.org"
  maintainer_url: "https://cvcpkg.org"
  homepage: https://xcb.freedesktop.org/
  license: MIT
  tags: [libraries, x11, graphics]
  description: >-
    XCB keysym conversion library (xcb-keysyms).

source:
  type: tarball
  url: https://xorg.freedesktop.org/releases/individual/xcb/xcb-util-keysyms-0.4.1.tar.xz
  sha256: "7c260a5294412aed429df1da2f8afd3bd07b7cba3fec772fba15a613a6d5c638"
  strip_components: 1

patches: []

depends:
  build:
    - pkg-config
  runtime:
    - name: libxcb
  host_tools: []

package:
  files:
    - lib/
    - include/
    - share/

build:
  matrix:
    - platform: linux
      script: build.sh
    - platform: freebsd
      script: build.sh
    - platform: openbsd
      script: build.sh
    - platform: netbsd
      script: build.sh
