# recipes/vcglib/build.ps1 — stage header-only vcglib into the prefix (Windows).
$ErrorActionPreference = "Stop"

$SRC = $env:CVC_SOURCE_DIR
$DST = $env:CVC_INSTALL_DIR

if (-not $SRC) { throw "CVC_SOURCE_DIR not set" }
if (-not $DST) { throw "CVC_INSTALL_DIR not set" }

# Create directories
New-Item -ItemType Directory -Force -Path "$DST\include"        | Out-Null
New-Item -ItemType Directory -Force -Path "$DST\share\vcglib"   | Out-Null
New-Item -ItemType Directory -Force -Path "$DST\share\cmake\vcglib" | Out-Null

# Header roots
Copy-Item -Recurse -Force "$SRC\vcg"  "$DST\include\vcg"
Copy-Item -Recurse -Force "$SRC\wrap" "$DST\include\wrap"

# Full source tree for add_subdirectory() consumers
Copy-Item -Recurse -Force "$SRC\*" "$DST\share\vcglib\"

# CMake package config
@'
# vcglib-config.cmake -- generated by cvcpkg (libcvc-deps)
include(CMakeFindDependencyMacro)
find_dependency(Eigen3 QUIET)

if(NOT TARGET vcglib::vcglib)
  add_library(vcglib::vcglib INTERFACE IMPORTED)
  get_filename_component(_vcglib_root
    "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
  set_target_properties(vcglib::vcglib PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${_vcglib_root}/include"
    INTERFACE_COMPILE_FEATURES    "cxx_std_11")
  if(MSVC)
    set_property(TARGET vcglib::vcglib APPEND PROPERTY
      INTERFACE_COMPILE_OPTIONS "/bigobj")
  endif()
  if(TARGET Eigen3::Eigen)
    set_property(TARGET vcglib::vcglib APPEND PROPERTY
      INTERFACE_LINK_LIBRARIES Eigen3::Eigen)
  endif()
endif()
'@ | Set-Content "$DST\share\cmake\vcglib\vcglib-config.cmake"

# CMake version file
$version = if ($env:CVC_VERSION) { $env:CVC_VERSION } else { "2025.07" }
@"
set(PACKAGE_VERSION "$version")
if("`${PACKAGE_FIND_VERSION}" STREQUAL "")
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
elseif("`${PACKAGE_FIND_VERSION}" VERSION_EQUAL "`${PACKAGE_VERSION}")
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
  set(PACKAGE_VERSION_EXACT TRUE)
elseif("`${PACKAGE_FIND_VERSION}" VERSION_LESS "`${PACKAGE_VERSION}")
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
else()
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
endif()
"@ | Set-Content "$DST\share\cmake\vcglib\vcglib-config-version.cmake"

Write-Host "vcglib $version staged into $DST"
